replicaCount: 2

ingress:
  enabled: false

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70  # Target CPU utilization percentage
  targetMemoryUtilizationPercentage: 70  # Target memory utilization percentage
resources:
  requests:
    memory: "16Mi"
    cpu: "20m"
  limits:
    memory: "32Mi"
    cpu: "40m"

# strategy:
maxSurge: 1
maxUnavailable: 0
minReadySeconds: 45
image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 80

istio:
  enabled: true
  gateway:
    name: nginx-gateway
    namespace: istio-system
  virtualService:
    hosts:
      - "*"
    gateways:
      - nginx-gateway
    http:
      - match:
          - uri:
              prefix: "/"
        route:
          - destination:
              host: nginx-chart
              port:
                number: 80



kuard:
  name: kuard-app
  image:
    repository:
    tag:
    pullPolicy: IfNotPresent
  resources:
    requests:
      memory: "16Mi"
      cpu: "20m"
    limits:
      memory: "32Mi"
      cpu: "40m"
  service:
    type: ClusterIP
    port: 8080