apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx-chart.fullname" . }}-config
  labels:
    app: {{ include "nginx-chart.name" . }}
data:
  default.conf: |-
{{ .Values.nginxConfig | indent 4 }}

