{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Values.istio.gateway.name }}
  namespace: {{ .Values.istio.gateway.namespace }}
spec:
  selector:
    istio: ingressgateway  # Use the default Istio ingress gateway
  servers:
    - port:
        number: {{ .Values.service.port }}
        name: http
        protocol: HTTP
      hosts:
        - "*"
{{- end }}

